<!-- TOC -->

- [错误处理](#%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86)
    - [用 throwing 函数传递错误](#%E7%94%A8-throwing-%E5%87%BD%E6%95%B0%E4%BC%A0%E9%80%92%E9%94%99%E8%AF%AF)
    - [用 Do-Catch 处理错误](#%E7%94%A8-do-catch-%E5%A4%84%E7%90%86%E9%94%99%E8%AF%AF)
    - [将错误转换成可选值](#%E5%B0%86%E9%94%99%E8%AF%AF%E8%BD%AC%E6%8D%A2%E6%88%90%E5%8F%AF%E9%80%89%E5%80%BC)
    - [禁用错误传递](#%E7%A6%81%E7%94%A8%E9%94%99%E8%AF%AF%E4%BC%A0%E9%80%92)

<!-- /TOC -->

# 错误处理

在 Swift 中，错误用遵循 `Error` 协议的类型的值来表示。
这个空协议表明该类型可以用于错误处理。

```swift
// 构建一组相关的错误状态
enum VendingMachineError: Error {
    case invalidSelection                     //选择无效
    case insufficientFunds(coinsNeeded: Int) //金额不足
    case outOfStock                             //缺货
}
```

```swift
// 抛出一个错误可以让你表明有意外情况发生，导致正常的执行流程无法继续执行。
throw VendingMachineError.insufficientFunds(coinsNeeded: 5)
```

4 种处理错误的方式

- 把函数抛出的错误传递给调用此函数的代码
- 用 do-catch 语句处理错误、
- 将错误作为可选类型处理、或者
- 断言此错误根本不会发生

## 用 throwing 函数传递错误

只有 throwing 函数可以传递错误。`任何在某个非 throwing 函数内部抛出的错误只能在函数内部处理`。

```swift
func canThrowErrors() throws -> String

func cannotThrowErrors() -> String
```

## 用 Do-Catch 处理错误

```swift
do {
    try expression
    statements
} catch pattern 1 {
    statements
} catch pattern 2 where condition {
    statements
} catch pattern 3, pattern 4 where condition {
    statements
} catch {
    statements
}
```

## 将错误转换成可选值

可以使用 try? 通过将错误转换成一个可选值来处理错误。如果是在计算 try? `表达式时抛出错误，该表达式的结果就为 nil`。

```swift
func someThrowingFunction() throws -> Int {
    // ...
}

let x = try? someThrowingFunction()
let y: Int?
do {
    y = try someThrowingFunction()
} catch {
    y = nil
}
```

## 禁用错误传递

```swift
let photo = try! loadImage(atPath: "./Resources/John Appleseed.jpg")
```

```swift

```
